/*
 * TreinPaneel.java
 *
 * Created on 22 november 2007, 12:35
 */

package gui;
import javax.swing.table.*;


/**
 *
 * @author  Fabian van den IJssel
 */
public class TreinPaneel extends javax.swing.JPanel {
    
    /** Creates new form TreinPaneel */
    public TreinPaneel() {
        
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTreinen = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Treinen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        setMaximumSize(new java.awt.Dimension(883, 173));
        setMinimumSize(new java.awt.Dimension(53, 81));

        tblTreinen.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tblTreinen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trein", "Aantal Reizigers", "Positie", "Vertrekpunt", "Bestemming"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTreinen.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblTreinen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        );
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable tblTreinen;
    // End of variables declaration//GEN-END:variables
 
    
    public DefaultTableModel getModel() {
        return (DefaultTableModel) this.tblTreinen.getModel();
    }
    
    /**
    * Zoekt een tabelregel bij de opgegeven trein
    * @param treinnr het nummer van de gezochte trein
    * @return de tabelregel van de gezochte trein
    */
    public int findTreinRow(int treinnr){
       try{ 
          for(int i = 0; i <= tblTreinen.getRowCount(); i++){
                if((Integer)tblTreinen.getValueAt(i, 0) == treinnr){
                 return i;
               }
         }
       }
        catch(Exception e){
           return -1;
        }
        
       return -1;
   
    }

}
